name: 'Zigbee Vent Mc'
packageKey: 'zigbee-vent'
description: 'Devices Supported: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-vent-mc/fingerprints.yml'
permissions:
  zigbee: {}
