name: 'Zigbee Multi Switch and Child Mc-immi'
packageKey: 'Zigbee_Multi_Switch-v5-immi'
description: 'Devices: https://github.com/Mariano-Github/Edge-Drivers-Beta/blob/main/zigbee-multi-switch-v4-childs-edge/fingerprints.yml'
permissions:
  zigbee: {}
