name: gen5-electric-meter-negative-values
components:
- id: main
  capabilities:
  - id: powerMeter
    version: 1
    config:
      values:
        - key: "power.value"
          range: [-15000, 15000]
  - id: energyMeter
    version: 1
    config:
      values:
        - key: "energy.value"
          range: [-50000, 50000]
  - id: voltageMeasurement
    version: 1
  - id: currentMeasurement
    version: 1
  - id: powerConsumptionReport
    version: 1
  - id: refresh
    version: 1
  categories:
  - name: CurbPowerMeter
preferences:
  - name: "selectiveReporting"
    title: "2. Solar Readings" 
    description: "This parameter 2 determines reports of power and energy. Default: Always positive "
    required: false
    preferenceType: enumeration
    definition:
      options:
        0: "Always positive"
        1: "Sum of positive & negative readings"
        2: "Only positive readings"
        3: "Only negative readings"
      default: 0
  - name: "thresholdWatt"
    title: "3. Threshold Readings" 
    description: "This parameter 3 determines disable selective reporting or enable automatic reports. Default: Disable"
    required: false
    preferenceType: enumeration
    definition:
      options:
        0: "Disable"
        1: "Enable"
      default: 0
  - name: "crcSixteen"
    title: "13. CRC-16" 
    description: "This parameter 13 determines reporting CRC-16 Encapsulation Command. Default: Disable"
    required: false
    preferenceType: enumeration
    definition:
      options:
        0: "Disable"
        1: "Enable"
      default: 0
  - name: "group1Time"
    title: "111. Group 1 Sensor Report Time"
    description: "This parameter 111 determine Group 1 time interval for automatic reports. Default: 300 sec"
    required: false
    preferenceType: integer
    definition:
      minimum: 0
      maximum: 86400
      default: 300
  - name: "configLock"
    title: "252. Settings Lock" 
    description: "This parameter 252 determines Disable or Enable settings lock. Default: Disable"
    required: false
    preferenceType: enumeration
    definition:
      options:
        0: "Disable"
        1: "Enable"
      default: 0